import { Book, VideoResource } from '@/types';
import { generateChapters } from './chapters';

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'ml-vol-1',
    title: '100 Days ML Notes (Vol. 1 - Core Foundations)',
    author: 'Ashutosh & ML Community',
    description: 'Volume 1 of the comprehensive 100 Days Machine Learning Handbook covering math foundations, regression, classification, decision trees, and feature engineering.',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1200&q=80',
    category: 'Textbook',
    status: 'COMPLETED',
    rating: 5.0,
    totalPages: 608,
    pagesPerChapter: 30,
    totalChapters: 21,
    chapters: generateChapters(608, 30),
    isBookmarked: true,
    isHot: true,
    isNew: true,
    pdfUrl: '/pdfs/100_days_ML_Notes_Vol1.pdf',
    uploadedAt: '2026-07-26T03:00:00Z',
  },
  {
    id: 'ml-vol-2',
    title: '100 Days ML Notes (Vol. 2 - Neural Networks)',
    author: 'Ashutosh & ML Community',
    description: 'Volume 2 covering deep learning architectures, backpropagation, convolutional neural networks (CNNs), activation functions, and optimizer algorithms.',
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    category: 'Textbook',
    status: 'COMPLETED',
    rating: 4.95,
    totalPages: 608,
    pagesPerChapter: 30,
    totalChapters: 21,
    chapters: generateChapters(608, 30),
    isBookmarked: true,
    isHot: true,
    isNew: true,
    pdfUrl: '/pdfs/100_days_ML_Notes_Vol2.pdf',
    uploadedAt: '2026-07-26T03:05:00Z',
  },
  {
    id: 'ml-vol-3',
    title: '100 Days ML Notes (Vol. 3 - Advanced AI & NLP)',
    author: 'Ashutosh & ML Community',
    description: 'Volume 3 diving into natural language processing, recurrent neural networks (RNNs/LSTMs), attention mechanisms, and transformer models.',
    coverImage: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1200&q=80',
    category: 'Textbook',
    status: 'COMPLETED',
    rating: 4.92,
    totalPages: 608,
    pagesPerChapter: 30,
    totalChapters: 21,
    chapters: generateChapters(608, 30),
    isBookmarked: false,
    isHot: false,
    isNew: true,
    pdfUrl: '/pdfs/100_days_ML_Notes_Vol3.pdf',
    uploadedAt: '2026-07-26T03:10:00Z',
  },
  {
    id: 'ml-vol-4',
    title: '100 Days ML Notes (Vol. 4 - MLOps & Deployment)',
    author: 'Ashutosh & ML Community',
    description: 'Volume 4 covering model deployment, system architecture, hyperparameter tuning, model monitoring, and Model Context Protocol (MCP) integrations.',
    coverImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    category: 'Textbook',
    status: 'COMPLETED',
    rating: 4.98,
    totalPages: 610,
    pagesPerChapter: 30,
    totalChapters: 21,
    chapters: generateChapters(610, 30),
    isBookmarked: false,
    isHot: false,
    isNew: true,
    pdfUrl: '/pdfs/100_days_ML_Notes_Vol4.pdf',
    uploadedAt: '2026-07-26T03:15:00Z',
  },
  {
    id: 'deep-learning-pdf',
    title: 'Deep Learning Practical Guide',
    author: 'AI Research Institute',
    description: 'Comprehensive deep learning guide with practical code examples, PyTorch tutorials, and computer vision implementation patterns.',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    category: 'Textbook',
    status: 'COMPLETED',
    rating: 4.88,
    totalPages: 350,
    pagesPerChapter: 20,
    totalChapters: 18,
    chapters: generateChapters(350, 20),
    isBookmarked: false,
    isHot: false,
    isNew: true,
    pdfUrl: '/pdfs/Deep_Learning.pdf',
    uploadedAt: '2026-07-26T02:00:00Z',
  },
  {
    id: 'mcp-pdf',
    title: 'Model Context Protocol (MCP) Specification',
    author: 'Anthropic & Open Source Standard',
    description: 'Official architectural specification and implementation guidelines for Model Context Protocol integrations and AI tools.',
    coverImage: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=600&q=80',
    category: 'Study PDF',
    status: 'COMPLETED',
    rating: 4.95,
    totalPages: 120,
    pagesPerChapter: 15,
    totalChapters: 8,
    chapters: generateChapters(120, 15),
    isBookmarked: true,
    isHot: false,
    isNew: true,
    pdfUrl: '/pdfs/Model_Context_Protocol.pdf',
    uploadedAt: '2026-07-26T01:00:00Z',
  },
  {
    id: 'book-1',
    title: 'Solo Leveling (Novel & Webtoon Vol. 1)',
    author: 'Chugong',
    description: 'In a world where hunters possessing magical powers must battle deadly monsters to protect the human race, weak hunter Sung Jinwoo finds himself in a struggle for survival.',
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1200&q=80',
    category: 'Manhwa',
    status: 'COMPLETED',
    rating: 4.9,
    totalPages: 240,
    pagesPerChapter: 12,
    totalChapters: 20,
    chapters: generateChapters(240, 12),
    isBookmarked: true,
    isHot: true,
    isNew: false,
    uploadedAt: '2026-07-20T10:00:00Z',
  }
];

export const INITIAL_VIDEOS: VideoResource[] = [
  {
    id: 'vid-1',
    title: 'Neural Networks & Deep Learning Explained visually',
    url: 'https://www.youtube.com/watch?v=aircAruvnKk',
    youtubeId: 'aircAruvnKk',
    category: 'ML',
    isWatched: false,
    addedAt: '2026-07-24T11:00:00Z',
    duration: '19:13',
    notes: 'Key concept: Matrix multiplication for weight updates and sigmoid vs ReLU activation functions.',
  },
  {
    id: 'vid-2',
    title: 'System Design Interview – Step by Step Guide',
    url: 'https://www.youtube.com/watch?v=bUHFg8CZFws',
    youtubeId: 'bUHFg8CZFws',
    category: 'Web Dev',
    isWatched: true,
    addedAt: '2026-07-23T15:20:00Z',
    duration: '45:00',
    notes: 'Load balancing strategies: Round Robin vs Least Connections.',
  },
  {
    id: 'vid-3',
    title: 'Linear Algebra for Machine Learning Full Course',
    url: 'https://www.youtube.com/watch?v=fNk_zzaMoSs',
    youtubeId: 'fNk_zzaMoSs',
    category: 'Math',
    isWatched: false,
    addedAt: '2026-07-25T08:30:00Z',
    duration: '1:12:40',
    notes: 'Eigenvalues and Eigenvectors decomposition in PCA.',
  }
];
