import { Book, VideoResource } from '@/types';
import { generateChapters } from './chapters';

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'book-1',
    title: 'Solo Leveling (Novel & Webtoon Vol. 1)',
    author: 'Chugong',
    description: 'In a world where hunters possessing magical powers must battle deadly monsters to protect the human race, weak hunter Sung Jinwoo finds himself in a struggle for survival.',
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1200&q=80',
    category: 'Manhwa',
    status: 'COMPLETED',
    rating: 4.9,
    totalPages: 240,
    pagesPerChapter: 12,
    totalChapters: 20,
    chapters: generateChapters(240, 12),
    isBookmarked: true,
    isHot: true,
    isNew: false,
    uploadedAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'book-2',
    title: 'The Beginning After The End Vol. 2',
    author: 'TurtleMe',
    description: 'King Grey has unrivaled strength, wealth, and prestige in a world governed by martial ability. However, solitude lingers closely behind those with great power.',
    coverImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    category: 'Manhwa',
    status: 'ONGOING',
    rating: 4.85,
    totalPages: 180,
    pagesPerChapter: 10,
    totalChapters: 18,
    chapters: generateChapters(180, 10),
    isBookmarked: true,
    isHot: true,
    isNew: true,
    uploadedAt: '2026-07-22T14:30:00Z',
  },
  {
    id: 'book-3',
    title: 'Machine Learning & Neural Networks Fundamentals',
    author: 'Dr. Alex Mercer',
    description: 'A comprehensive study manual covering backpropagation, transformer architectures, gradient descent optimization, and practical PyTorch examples.',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
    category: 'Textbook',
    status: 'ONGOING',
    rating: 4.95,
    totalPages: 320,
    pagesPerChapter: 16,
    totalChapters: 20,
    chapters: generateChapters(320, 16),
    isBookmarked: false,
    isHot: false,
    isNew: true,
    uploadedAt: '2026-07-24T09:15:00Z',
  },
  {
    id: 'book-4',
    title: 'Omniscient Reader\'s Viewpoint',
    author: 'sing N song',
    description: 'Kim Dokja was an average office worker whose only hobby was reading his favorite web novel. But when the story suddenly becomes reality, he is the only person who knows how the world will end.',
    coverImage: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=600&q=80',
    category: 'Manhwa',
    status: 'ONGOING',
    rating: 4.92,
    totalPages: 210,
    pagesPerChapter: 14,
    totalChapters: 15,
    chapters: generateChapters(210, 14),
    isBookmarked: true,
    isHot: true,
    isNew: false,
    uploadedAt: '2026-07-15T08:00:00Z',
  },
  {
    id: 'book-5',
    title: 'System Design Architecture & Distributed Systems',
    author: 'Martin Kleppmann Style Guide',
    description: 'Essential reference guide for building scalable, reliable, and maintainable web applications, databases, caching layers, and microservices.',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    category: 'Study PDF',
    status: 'COMPLETED',
    rating: 4.88,
    totalPages: 150,
    pagesPerChapter: 15,
    totalChapters: 10,
    chapters: generateChapters(150, 15),
    isBookmarked: false,
    isHot: false,
    isNew: false,
    uploadedAt: '2026-07-10T12:00:00Z',
  }
];

export const INITIAL_VIDEOS: VideoResource[] = [
  {
    id: 'vid-1',
    title: 'Neural Networks & Deep Learning Explained visually',
    url: 'https://www.youtube.com/watch?v=aircAruvnKk',
    youtubeId: 'aircAruvnKk',
    category: 'ML',
    isWatched: false,
    addedAt: '2026-07-24T11:00:00Z',
    duration: '19:13',
    notes: 'Key concept: Matrix multiplication for weight updates and sigmoid vs ReLU activation functions.',
  },
  {
    id: 'vid-2',
    title: 'System Design Interview – Step by Step Guide',
    url: 'https://www.youtube.com/watch?v=bUHFg8CZFws',
    youtubeId: 'bUHFg8CZFws',
    category: 'Web Dev',
    isWatched: true,
    addedAt: '2026-07-23T15:20:00Z',
    duration: '45:00',
    notes: 'Load balancing strategies: Round Robin vs Least Connections.',
  },
  {
    id: 'vid-3',
    title: 'Linear Algebra for Machine Learning Full Course',
    url: 'https://www.youtube.com/watch?v=fNk_zzaMoSs',
    youtubeId: 'fNk_zzaMoSs',
    category: 'Math',
    isWatched: false,
    addedAt: '2026-07-25T08:30:00Z',
    duration: '1:12:40',
    notes: 'Eigenvalues and Eigenvectors decomposition in PCA.',
  }
];
